name: "Build image: dapp-dev"

on:
  workflow_dispatch:
  push: 
    branches: [master]
    paths:
      - token-distributor/**
      - .github/workflows/build-docker-token-dist.yaml

jobs:
  build-and-push-dapp-dev-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/token-dist:latest
          file: ./token-distributor/Dockerfile
          context: token-distributor
